name: external-cache

on:
  schedule:
    - cron: "0 10 * * *" # UTC
  workflow_dispatch:

jobs:
  clear-workflow-external-cache:
    runs-on:
      - ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: cleanup caches
        # https://github.com/actions/cache/blob/main/tips-and-workarounds.md#force-deletion-of-caches-overriding-default-cache-eviction-policy
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh cache delete --all --succeed-on-no-caches \
            --repo ${{ github.repository }}

  refresh-workflow-external-cache:
    needs:
      - clear-workflow-external-cache
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-latest"
          - os: "macos-latest"
    runs-on: ${{ matrix.os }}
    permissions:
      actions: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/ci-env-setup
        with:
          buildbuddy-api-key: ${{ secrets.BUILDBUDDY_API_KEY }}

      - name: fetch external deps
        run: |
          bazel vendor \
            --vendor_dir=~/bazel_external_deps \
            --curses=yes \
            //...

      - uses: nix-community/cache-nix-action/save@v6
        with:
          paths: |
            ~/bazel_external_deps
            /nix
            ~/.cache/nix
            ~root/.cache/nix
          primary-key: bazel-external-cache-${{ runner.os }}-default
